### PR TITLE
Add ability to use startTime in Akoma Ntoso output

### PR DESCRIPTION
**Pull request by patcon**
Hello! I've spent a bit of time in the past few days trying to track along between the recorded videos and the SayIt transcripts passed through Google Translate. I love love love what's available, but it's currently quite difficult to sync things up.

My thought was that it might be a step in the right direction to accommodate rough timestamp parsing and extrapolation into pad2an, using some TBD syntax.

I'm unsure whether either relative or absolute would be best. (NA only allows absolute datetimes.) Which is best depends whether transcribers are working from the recorded video (relative is simpler) or the live event (absolute is simpler).

My thoughts would be to allow datetimes of some sort to be entered at arbitrary points in the hackpad transcript, and then to roughly derive start and end times from that for each NA speech element.

This would:

1. allow SayIt to rough out the timestamps and [present them like seen here](http://vkanata.sayit.mysociety.org/2015-10-01-airbnb-%E8%87%AA%E7%94%A8%E4%BD%8F%E5%AE%85%E6%8B%9B%E7%A7%9F%E6%84%8F%E8%A6%8B%E5%BE%B5%E9%9B%86%E8%AB%AE%E8%A9%A2%E6%9C%83%E8%AD%B0)
2. allow further processing into YouTube compatible transcript formats, which could be imported back onto YouTube videos. (I believe auto-translation would then be possible on that platform.)

(As a side-note, a clock in the corner of the video stream layouts would also greatly help folks in my position, trying to match things up. For now, I assumed the meeting started exactly on schedule :smile: )

### CODE REVIEW

**Comment by patcon** [comment]
okie dokie, so I ended up doing something a little simpler, by leaving out the extrapolative bit. I'd be happy to add if we start using this and find it helpful!

Here's a samplel transcript pad:
https://hackpad.com/2015-10-01-Airbnb--P8JIVOnuM2i

Basically, the transcriber can add as little or as many timecodes in hh:mm:ss format as they'd like, so help readers with wayfinding.

```
## Transcript

⌛ 2015-10-01T18:51:00

Audrey Tang:
* Saying things.

Mike Orgill: 01:48:31
* Saying other thingies.
```

Sorry if the style is a messy, as I'm only vaguely familiar with functional programming practices (and even async programming isn't something I'm so comfortable with..!)

Def let me know if I can fix/clean anything up! Happy to squash commits more sensibly if you'd prefer.

**Comment by patcon** [comment]
Hm. Actually, seems that SayIt may ignore or re-order speech entries without startTime's which I didn't expect -- so this isn't ready for review. Sorry for the noise!

**Comment by patcon** [comment]
Given that the extrapolative bit seems to be required to make this work, any suggestion on how to estimate speaking time from transcripts when it's a mix of English and Mandarin? Would it suffice to treat whitespace separated words as the proxy for time units in English (`/[\u0000-\u007F]+/`) and individual Non-English characters (`/^[\u0000-\u007F]+/`) as the time unit proxy for Mandarin?

**Comment by audreyt** [comment]
It's an useful proxy, of course. Alternately we can count the number of continuous vowels /[aeiou]+/.

**Comment by patcon** [comment]
Great idea. Current status: torn between deterministic behaviour and being clever.

```livescript
sometimes-y = if Math.random! > 0.5 then 'y' else ''
count = html.match //[aeiou#{sometimes-y}]+//g
```

**Comment by audreyt** [comment]
Deterministically `y` can count as half a point.

**Comment by patcon** [comment]
Touche

**Pull request merged**
